# config

# interval in mins
interval: 5

# bbdc account username and password
bbdc:
  username: "your username"
  password: "your password"

# telegram bot link
telegram:
  # enable or disable telegram bot
  enabled: True
  
  # token id and chat id for telegram bot refer to telegram bot guide
  token: "16857xxxxx:AAFJ5A0uP5Mo78tL1rxxxxxxxxxxxx"
  chat_id: "-5922xxxxx"
